export type BuildingCategory =
  | "extraction"
  | "industry"
  | "logistics"
  | "residential"
  | "tech"
  | "culture"
  | "military";

export type BuildingStatus = "existing" | "locked";

export type HierarchyRole = "trabajador" | "supervisor" | "administrador" | "maestro";

export interface StoredItem {
  id: string;
  name: string;
  icon: string;
  quantity: number;
  maxCapacity: number;
  unit: string;
  category: string;
}

export interface WorkerSlot {
  id: string;
  npcId?: string;
  npcName?: string;
  professionRequired: string;
  role: HierarchyRole;
  efficiency: number; // 0% a 100%
  assignedAt?: string;
}

export interface BuildingRecipe {
  inputs: { name: string; icon: string; rate: string }[];
  outputs: { name: string; icon: string; rate: string }[];
  durationSec: number;
}

export interface BuildingData {
  id: string;
  name: string;
  category: BuildingCategory;
  categoryLabel: string;
  categoryIcon: string;
  status: BuildingStatus;
  tier: number;
  icon: string;
  description: string;
  durability: number;
  maxDurability: number;
  efficiency: number; // 0-100%
  level: number;
  maxWorkers: number;
  workers: WorkerSlot[];
  inventory: StoredItem[];
  maxInventoryWeight: number;
  recipe?: BuildingRecipe;
  unlockCost?: { name: string; amount: number; icon: string }[];
  location?: { x: number; y: number };
}

export const CATEGORY_INFO: Record<BuildingCategory, { label: string; icon: string; color: string }> = {
  extraction: { label: "Recolección y Extracción", icon: "🚜", color: "#66bb6a" },
  industry: { label: "Refinación Industrial", icon: "🏭", color: "#ffa726" },
  logistics: { label: "Almacenamiento y Logística", icon: "📦", color: "#42a5f5" },
  residential: { label: "Civil y Residencial", icon: "🏠", color: "#ab47bc" },
  tech: { label: "Ciencia y Tecnología", icon: "🎓", color: "#26c6da" },
  culture: { label: "Cultura y Religión", icon: "🎨", color: "#ec407a" },
  military: { label: "Militar y Defensivo", icon: "🛡️", color: "#ef5350" },
};

export const INITIAL_BUILDINGS: BuildingData[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // 1. RECOLECCIÓN Y EXTRACCIÓN (MATERIAS PRIMAS Y AGRICULTURA)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_cropplot",
    name: "Parcela de Cultivo",
    category: "extraction",
    categoryLabel: "Agricultura",
    categoryIcon: "🌱",
    status: "existing",
    tier: 1,
    icon: "🌱",
    description: "Tierra arada y fertilizada lista para sembrar cereales, hortalizas, frutas y plantas industriales. Ciclo de 24 horas con 4 fases de crecimiento.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 600,
    workers: [
      { id: "w1", professionRequired: "Agricultor", role: "trabajador", efficiency: 100 },
      { id: "w2", professionRequired: "Agricultor", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "seeds_wheat", name: "Semillas de Trigo", icon: "🌾", quantity: 20, maxCapacity: 200, unit: "uds", category: "Semillas" },
      { id: "fertilizer", name: "Abono Orgánico", icon: "🍂", quantity: 15, maxCapacity: 100, unit: "sacos", category: "Insumo" },
    ],
    recipe: {
      inputs: [{ name: "Agua", icon: "💧", rate: "2 L/día" }, { name: "Semillas", icon: "🌱", rate: "1 ud/siembra" }],
      outputs: [{ name: "Cosecha Agrícola", icon: "🌾", rate: "Variable (24h)" }],
      durationSec: 86400,
    },
    unlockCost: [{ name: "Madera", amount: 10, icon: "🪵" }, { name: "Piedra", amount: 5, icon: "🪨" }],
  },
  {
    id: "b_woodcamp",
    name: "Cabaña de Leñadores",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🪓",
    description: "Tala de árboles y reforestación controlada.",
    durability: 100,
    maxDurability: 100,
    efficiency: 95,
    level: 1,
    maxWorkers: 4,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", npcName: "Garin el Fuerte", professionRequired: "Leñador", role: "supervisor", efficiency: 100 },
      { id: "w2", npcName: "Bryn", professionRequired: "Leñador", role: "trabajador", efficiency: 85 },
      { id: "w3", professionRequired: "Leñador", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Leñador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "wood_log", name: "Troncos de Roble", icon: "🪵", quantity: 140, maxCapacity: 400, unit: "uds", category: "Madera" },
      { id: "firewood", name: "Leña Cortada", icon: "🔥", quantity: 85, maxCapacity: 250, unit: "uds", category: "Combustible" },
      { id: "resin", name: "Resina Natural", icon: "🧪", quantity: 18, maxCapacity: 50, unit: "frascos", category: "Químico" },
    ],
    recipe: {
      inputs: [{ name: "Hacha", icon: "🪓", rate: "1 des/h" }],
      outputs: [{ name: "Troncos", icon: "🪵", rate: "+24/h" }, { name: "Leña", icon: "🔥", rate: "+12/h" }],
      durationSec: 15,
    },
    location: { x: 3200, y: 3100 },
  },
  {
    id: "b_stonequarry",
    name: "Cantera de Piedra",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "⛏️",
    description: "Extracción de bloques de piedra y caliza.",
    durability: 90,
    maxDurability: 100,
    efficiency: 80,
    level: 1,
    maxWorkers: 4,
    maxInventoryWeight: 1200,
    workers: [
      { id: "w1", npcName: "Torvald Cantero", professionRequired: "Minero", role: "supervisor", efficiency: 90 },
      { id: "w2", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "stone_raw", name: "Piedra en Bruto", icon: "🪨", quantity: 210, maxCapacity: 600, unit: "kg", category: "Mineral" },
      { id: "limestone", name: "Piedra Caliza", icon: "🧱", quantity: 45, maxCapacity: 200, unit: "bloques", category: "Construcción" },
    ],
    recipe: {
      inputs: [{ name: "Picos", icon: "⛏️", rate: "1 des/2h" }],
      outputs: [{ name: "Piedra", icon: "🪨", rate: "+18/h" }, { name: "Caliza", icon: "🧱", rate: "+6/h" }],
      durationSec: 20,
    },
    location: { x: 3450, y: 2900 },
  },
  {
    id: "b_coalmine",
    name: "Mina de Carbón",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "locked",
    tier: 2,
    icon: "⬛",
    description: "Extracción de combustible fósil para la industria.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 1000,
    workers: [
      { id: "w1", professionRequired: "Minero", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "coal", name: "Carbón Mineral", icon: "⬛", quantity: 0, maxCapacity: 600, unit: "kg", category: "Combustible" },
    ],
    unlockCost: [{ name: "Madera", amount: 80, icon: "🪵" }, { name: "Piedra", amount: 60, icon: "🪨" }],
  },
  {
    id: "b_ironmine",
    name: "Mina de Hierro",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "locked",
    tier: 2,
    icon: "🔩",
    description: "Obtención de menas metálicas básicas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 6,
    maxInventoryWeight: 1500,
    workers: [
      { id: "w1", professionRequired: "Maestro Minero", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Minero", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w5", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w6", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "iron_ore", name: "Mena de Hierro", icon: "🪨", quantity: 0, maxCapacity: 800, unit: "kg", category: "Mineral" },
    ],
    unlockCost: [{ name: "Troncos", amount: 100, icon: "🪵" }, { name: "Piedra", amount: 80, icon: "🧱" }],
  },
  {
    id: "b_preciousmine",
    name: "Mina de Metales Preciosos",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "locked",
    tier: 3,
    icon: "💎",
    description: "Extracción de oro, plata y gemas preciosas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 600,
    workers: [
      { id: "w1", professionRequired: "Prospector Experto", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Minero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "gold_ore", name: "Oro en Bruto", icon: "🥇", quantity: 0, maxCapacity: 200, unit: "kg", category: "Precioso" },
      { id: "silver_ore", name: "Plata en Bruto", icon: "🥈", quantity: 0, maxCapacity: 200, unit: "kg", category: "Precioso" },
      { id: "gems", name: "Gemas sin Tallar", icon: "💎", quantity: 0, maxCapacity: 50, unit: "uds", category: "Joyería" },
    ],
    unlockCost: [{ name: "Vigas de Madera", amount: 80, icon: "🏗️" }, { name: "Piedra Labrada", amount: 120, icon: "🧱" }],
  },
  {
    id: "b_sulfurmine",
    name: "Mina de Azufre y Salitre",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "locked",
    tier: 3,
    icon: "🌋",
    description: "Recolección de componentes para la pólvora.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", professionRequired: "Alquimista Minero", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "sulfur", name: "Azufre Puro", icon: "🟡", quantity: 0, maxCapacity: 200, unit: "kg", category: "Químico" },
      { id: "saltpeter", name: "Salitre", icon: "🧂", quantity: 0, maxCapacity: 200, unit: "kg", category: "Químico" },
    ],
    unlockCost: [{ name: "Tablones", amount: 70, icon: "🪵" }, { name: "Piedra", amount: 90, icon: "🧱" }],
  },
  {
    id: "b_claypit",
    name: "Pozo de Arcilla",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🏺",
    description: "Extracción de materia prima para cerámica y ladrillos.",
    durability: 95,
    maxDurability: 100,
    efficiency: 85,
    level: 1,
    maxWorkers: 3,
    maxInventoryWeight: 700,
    workers: [
      { id: "w1", npcName: "Milo Alfarero", professionRequired: "Excavador", role: "supervisor", efficiency: 90 },
      { id: "w2", professionRequired: "Excavador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Excavador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "clay", name: "Arcilla Húmeda", icon: "🟫", quantity: 80, maxCapacity: 400, unit: "kg", category: "Materia Prima" },
    ],
    location: { x: 3100, y: 3300 },
  },
  {
    id: "b_pumpingstation",
    name: "Noria / Estación de Bombeo",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🚰",
    description: "Extracción masiva de agua dulce para riego y población.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 1000,
    workers: [
      { id: "w1", npcName: "Elisa", professionRequired: "Operador de Noria", role: "supervisor", efficiency: 100 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "fresh_water", name: "Agua Dulce", icon: "💧", quantity: 450, maxCapacity: 1000, unit: "litros", category: "Líquidos" },
    ],
    location: { x: 3050, y: 3080 },
  },
  {
    id: "b_huntinglodge",
    name: "Cabaña de Caza",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🏹",
    description: "Obtención de carne, pieles y tendones.",
    durability: 85,
    maxDurability: 100,
    efficiency: 85,
    level: 1,
    maxWorkers: 3,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", npcName: "Rowan Cazador", professionRequired: "Cazador", role: "supervisor", efficiency: 90 },
      { id: "w2", professionRequired: "Cazador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Cazador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "raw_meat", name: "Carne Cruda", icon: "🥩", quantity: 65, maxCapacity: 200, unit: "kg", category: "Comida" },
      { id: "pelt", name: "Pieles de Bestia", icon: "🐺", quantity: 30, maxCapacity: 100, unit: "pieles", category: "Cuero" },
      { id: "sinew", name: "Tendones y Fibras", icon: "🧵", quantity: 20, maxCapacity: 80, unit: "uds", category: "Componente" },
    ],
    location: { x: 2750, y: 2950 },
  },
  {
    id: "b_foragingpost",
    name: "Puesto de Recolección Silvestre",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🌿",
    description: "Recogida de plantas medicinales, bayas y hongos.",
    durability: 90,
    maxDurability: 100,
    efficiency: 80,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", npcName: "Nerea Botánica", professionRequired: "Recolector", role: "supervisor", efficiency: 85 },
      { id: "w2", professionRequired: "Recolector", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "herbs", name: "Hierbas Medicinales", icon: "🌿", quantity: 45, maxCapacity: 150, unit: "manojos", category: "Medicina" },
      { id: "berries", name: "Bayas Silvestres", icon: "🍒", quantity: 60, maxCapacity: 150, unit: "canastos", category: "Comida" },
    ],
    location: { x: 2850, y: 3100 },
  },
  {
    id: "b_fishery",
    name: "Pescadería / Muelle de Pesca",
    category: "extraction",
    categoryLabel: "Recolección",
    categoryIcon: "🚜",
    status: "existing",
    tier: 1,
    icon: "🎣",
    description: "Extracción de recursos alimenticios marítimos o fluviales.",
    durability: 95,
    maxDurability: 100,
    efficiency: 90,
    level: 1,
    maxWorkers: 3,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", npcName: "Kael Pescador", professionRequired: "Pescador", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Pescador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Pescador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "fish_raw", name: "Pescado Fresco", icon: "🐟", quantity: 110, maxCapacity: 300, unit: "kg", category: "Comida" },
      { id: "fish_oil", name: "Aceite de Pescado", icon: "🛢️", quantity: 25, maxCapacity: 80, unit: "frascos", category: "Combustible" },
    ],
    location: { x: 3400, y: 3200 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 2. REFINACIÓN Y PROCESAMIENTO INDUSTRIAL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_sawmill",
    name: "Aserradero",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "existing",
    tier: 1,
    icon: "🪚",
    description: "Transformación de troncos en tablas y vigas estructurales.",
    durability: 95,
    maxDurability: 100,
    efficiency: 90,
    level: 1,
    maxWorkers: 3,
    maxInventoryWeight: 900,
    workers: [
      { id: "w1", npcName: "Finn Carpintero", professionRequired: "Carpintero", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Carpintero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Carpintero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "planks", name: "Tablas de Madera", icon: "🪵", quantity: 180, maxCapacity: 400, unit: "tablas", category: "Construcción" },
      { id: "beams", name: "Vigas Estructurales", icon: "🏗️", quantity: 40, maxCapacity: 120, unit: "vigas", category: "Construcción" },
    ],
    location: { x: 3180, y: 3160 },
  },
  {
    id: "b_charcoalpit",
    name: "Carbonera (Foso de Carbón)",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "existing",
    tier: 1,
    icon: "🔥",
    description: "Quema de madera para crear carbón vegetal.",
    durability: 90,
    maxDurability: 100,
    efficiency: 85,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 600,
    workers: [
      { id: "w1", npcName: "Bran Carbonero", professionRequired: "Carbonero", role: "supervisor", efficiency: 90 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "charcoal", name: "Carbón Vegetal", icon: "⬛", quantity: 120, maxCapacity: 300, unit: "sacos", category: "Combustible" },
    ],
    location: { x: 3250, y: 3150 },
  },
  {
    id: "b_brickkiln",
    name: "Horno de Ladrillos",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 2,
    icon: "🧱",
    description: "Cocción de arcilla para materiales de construcción avanzados.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", professionRequired: "Maestro Hornero", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "bricks", name: "Ladrillos Cocidos", icon: "🧱", quantity: 0, maxCapacity: 400, unit: "bloques", category: "Construcción" },
      { id: "tiles", name: "Tejas de Cerámica", icon: "🟫", quantity: 0, maxCapacity: 300, unit: "tejas", category: "Construcción" },
    ],
    unlockCost: [{ name: "Piedra", amount: 70, icon: "🪨" }, { name: "Arcilla", amount: 50, icon: "🟫" }],
  },
  {
    id: "b_smelter",
    name: "Altorno de Fundición",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 2,
    icon: "🌋",
    description: "Separación del metal puro de la roca (lingotes).",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 1000,
    workers: [
      { id: "w1", professionRequired: "Fundidor Experto", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "iron_ingot", name: "Lingotes de Hierro", icon: "🥈", quantity: 0, maxCapacity: 300, unit: "lingotes", category: "Metal" },
      { id: "copper_ingot", name: "Lingotes de Cobre", icon: "🥉", quantity: 0, maxCapacity: 200, unit: "lingotes", category: "Metal" },
    ],
    unlockCost: [{ name: "Piedra Labrada", amount: 100, icon: "🧱" }, { name: "Carbón", amount: 40, icon: "⬛" }],
  },
  {
    id: "b_forge",
    name: "Forja Industrial",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 2,
    icon: "🔨",
    description: "Moldeado de metales en planchas, clavos y herramientas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 700,
    workers: [
      { id: "w1", professionRequired: "Maestro Herrero", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Aprendiz", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Aprendiz", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "iron_plates", name: "Planchas de Metal", icon: "🛡️", quantity: 0, maxCapacity: 100, unit: "placas", category: "Industria" },
      { id: "tools", name: "Herramientas de Hierro", icon: "🔨", quantity: 0, maxCapacity: 80, unit: "uds", category: "Herramientas" },
    ],
    unlockCost: [{ name: "Lingotes de Hierro", amount: 30, icon: "🥈" }, { name: "Tablas", amount: 60, icon: "🪵" }],
  },
  {
    id: "b_tannery",
    name: "Curtiduría",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 1,
    icon: "🧥",
    description: "Tratamiento de pieles crudas para convertirlas en cuero.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 400,
    workers: [
      { id: "w1", professionRequired: "Curtidor", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "leather", name: "Cuero Curtido", icon: "🟫", quantity: 0, maxCapacity: 150, unit: "planchas", category: "Materiales" },
    ],
    unlockCost: [{ name: "Madera", amount: 40, icon: "🪵" }, { name: "Pieles", amount: 15, icon: "🐺" }],
  },
  {
    id: "b_textilemill",
    name: "Taller de Hilandería",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 1,
    icon: "🧵",
    description: "Procesamiento de lana, lino o algodón en hilos y telas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 350,
    workers: [
      { id: "w1", professionRequired: "Hilador", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "thread", name: "Carretes de Hilo", icon: "🧵", quantity: 0, maxCapacity: 200, unit: "carretes", category: "Textil" },
      { id: "cloth", name: "Rollos de Tela", icon: "🧶", quantity: 0, maxCapacity: 100, unit: "rollos", category: "Textil" },
    ],
    unlockCost: [{ name: "Madera", amount: 40, icon: "🪵" }],
  },
  {
    id: "b_grainmill",
    name: "Molino de Grano (Harinero)",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "existing",
    tier: 1,
    icon: "💨",
    description: "Procesamiento de trigo y cereales para consumo humano.",
    durability: 95,
    maxDurability: 100,
    efficiency: 90,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 600,
    workers: [
      { id: "w1", npcName: "Otto Molinero", professionRequired: "Molinero", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Molinero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "flour", name: "Harina Fina", icon: "🥡", quantity: 95, maxCapacity: 250, unit: "sacos", category: "Alimento" },
    ],
    location: { x: 2980, y: 3250 },
  },
  {
    id: "b_glassblowing",
    name: "Taller de Soplado de Vidrio",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 2,
    icon: "🧪",
    description: "Creación de recipientes, ventanas y material de laboratorio.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", professionRequired: "Vidriero", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Aprendiz", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "vials", name: "Frascos de Vidrio", icon: "🧪", quantity: 0, maxCapacity: 150, unit: "frascos", category: "Alquimia" },
      { id: "window_glass", name: "Paneles de Vidrio", icon: "🪟", quantity: 0, maxCapacity: 60, unit: "paneles", category: "Construcción" },
    ],
    unlockCost: [{ name: "Piedra", amount: 60, icon: "🪨" }, { name: "Carbón", amount: 30, icon: "⬛" }],
  },
  {
    id: "b_alchemyrefinery",
    name: "Refinería de Alquimia",
    category: "industry",
    categoryLabel: "Industria",
    categoryIcon: "🏭",
    status: "locked",
    tier: 3,
    icon: "⚗️",
    description: "Destilación de aceites, ácidos y combustibles químicos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 400,
    workers: [
      { id: "w1", professionRequired: "Gran Alquimista", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Boticario", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Asistente", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "alchemical_oil", name: "Aceite Refinado", icon: "🛢️", quantity: 0, maxCapacity: 100, unit: "frascos", category: "Químico" },
      { id: "gunpowder", name: "Pólvora Negra", icon: "💣", quantity: 0, maxCapacity: 80, unit: "barriles", category: "Militar" },
    ],
    unlockCost: [{ name: "Vidrio", amount: 40, icon: "🧪" }, { name: "Azufre", amount: 30, icon: "🟡" }],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 3. ALMACENAMIENTO Y LOGÍSTICA
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_stockpile",
    name: "Pila de Troncos / Piedra",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "existing",
    tier: 1,
    icon: "🪵",
    description: "Almacenamiento básico a cielo abierto para recursos brutos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 1500,
    workers: [
      { id: "w1", npcName: "Tomas", professionRequired: "Portador", role: "trabajador", efficiency: 90 },
      { id: "w2", professionRequired: "Portador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "bulk_wood", name: "Pila de Madera", icon: "🪵", quantity: 300, maxCapacity: 800, unit: "troncos", category: "Bruto" },
      { id: "bulk_stone", name: "Pila de Roca", icon: "🪨", quantity: 200, maxCapacity: 700, unit: "rocas", category: "Bruto" },
    ],
    location: { x: 3120, y: 3050 },
  },
  {
    id: "b_grainsilo",
    name: "Silo de Grano",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "existing",
    tier: 1,
    icon: "🌾",
    description: "Almacenamiento ventilado para evitar que la comida se eche a perder.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 2000,
    workers: [
      { id: "w1", npcName: "Klaus", professionRequired: "Guardián de Silo", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Trabajador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "stored_grain", name: "Granos de Trigo Seco", icon: "🌾", quantity: 550, maxCapacity: 1500, unit: "kg", category: "Cereales" },
    ],
    location: { x: 2950, y: 3200 },
  },
  {
    id: "b_warehouse",
    name: "Almacén Central",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "existing",
    tier: 1,
    icon: "📦",
    description: "Depósito techado para bienes procesados y herramientas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 4,
    maxInventoryWeight: 3000,
    workers: [
      { id: "w1", npcName: "Albar el Intendente", professionRequired: "Administrador", role: "administrador", efficiency: 100 },
      { id: "w2", professionRequired: "Portador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Portador", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Portador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "mixed_crates", name: "Cajas de Suministros", icon: "📦", quantity: 24, maxCapacity: 100, unit: "cajas", category: "Varios" },
      { id: "stone_reserve", name: "Reserva de Piedra", icon: "🪨", quantity: 150, maxCapacity: 500, unit: "kg", category: "Mineral" },
      { id: "wood_reserve", name: "Reserva de Madera", icon: "🪵", quantity: 200, maxCapacity: 500, unit: "uds", category: "Madera" },
    ],
    location: { x: 3072, y: 3072 },
  },
  {
    id: "b_treasuryvault",
    name: "Cámara Acorazada (Tesorería)",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "locked",
    tier: 3,
    icon: "🏛️",
    description: "Almacenamiento seguro para el oro y la riqueza del imperio.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 1000,
    workers: [
      { id: "w1", professionRequired: "Tesorero Real", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Guardia Juramentado", role: "supervisor", efficiency: 0 },
    ],
    inventory: [
      { id: "treasury_gold", name: "Lingotes de Oro Acuñados", icon: "💰", quantity: 0, maxCapacity: 10000, unit: "monedas", category: "Tesoro" },
    ],
    unlockCost: [{ name: "Piedra Labrada", amount: 150, icon: "🧱" }, { name: "Planchas de Metal", amount: 50, icon: "🛡️" }],
  },
  {
    id: "b_cartstation",
    name: "Estación de Carretas / Caballerizas",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "locked",
    tier: 2,
    icon: "🐎",
    description: "Centro logístico para rutas comerciales internas de colonos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 1200,
    workers: [
      { id: "w1", professionRequired: "Maestro Carretero", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Cochero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Cochero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "carts", name: "Carretas de Bueyes", icon: "🛒", quantity: 0, maxCapacity: 10, unit: "carretas", category: "Transporte" },
    ],
    unlockCost: [{ name: "Tablas", amount: 80, icon: "🪵" }, { name: "Herrajes", amount: 20, icon: "🔩" }],
  },
  {
    id: "b_tradingport",
    name: "Puerto Comercial",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "locked",
    tier: 3,
    icon: "⛵",
    description: "Punto de carga y descarga para barcos de gran calado.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 5,
    maxInventoryWeight: 4000,
    workers: [
      { id: "w1", professionRequired: "Capitán de Puerto", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Estibador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Estibador", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Estibador", role: "trabajador", efficiency: 0 },
      { id: "w5", professionRequired: "Estibador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "import_goods", name: "Cargamento de Ultramar", icon: "📦", quantity: 0, maxCapacity: 2000, unit: "fardos", category: "Comercio" },
    ],
    unlockCost: [{ name: "Vigas", amount: 120, icon: "🏗️" }, { name: "Piedra", amount: 150, icon: "🧱" }],
  },
  {
    id: "b_craneelevator",
    name: "Estación de Grúas y Elevadores",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "locked",
    tier: 2,
    icon: "🏗️",
    description: "Mueve recursos verticalmente entre acantilados y minas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", professionRequired: "Mecánico de Poleas", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Operario", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "cables", name: "Cables y Poleas", icon: "⚙️", quantity: 0, maxCapacity: 30, unit: "conjuntos", category: "Mecánica" },
    ],
    unlockCost: [{ name: "Vigas", amount: 60, icon: "🏗️" }, { name: "Cuerdas", amount: 40, icon: "🧵" }],
  },
  {
    id: "b_fluidtank",
    name: "Depósito de Fluidos",
    category: "logistics",
    categoryLabel: "Logística",
    categoryIcon: "📦",
    status: "locked",
    tier: 2,
    icon: "🛢️",
    description: "Cisternas selladas para almacenar agua, aceites o químicos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 1,
    maxInventoryWeight: 3000,
    workers: [
      { id: "w1", professionRequired: "Custodio de Tanques", role: "supervisor", efficiency: 0 },
    ],
    inventory: [
      { id: "tank_water", name: "Reserva de Agua Dulce", icon: "💧", quantity: 0, maxCapacity: 3000, unit: "litros", category: "Líquido" },
    ],
    unlockCost: [{ name: "Piedra", amount: 80, icon: "🪨" }, { name: "Arcilla", amount: 40, icon: "🟫" }],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 4. CIVIL, RESIDENCIAL Y SERVICIOS
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_tier1huts",
    name: "Campamento de Chozas (Tier 1)",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "existing",
    tier: 1,
    icon: "🛖",
    description: "Viviendas precarias para la mano de obra inicial.",
    durability: 85,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 0,
    maxInventoryWeight: 200,
    workers: [],
    inventory: [
      { id: "personal_belongings", name: "Enseres de Colonos", icon: "🎒", quantity: 30, maxCapacity: 100, unit: "bolsas", category: "Doméstico" },
    ],
    location: { x: 3020, y: 3050 },
  },
  {
    id: "b_tier2houses",
    name: "Casas de Piedra (Tier 2)",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "locked",
    tier: 2,
    icon: "🏡",
    description: "Residencias urbanas estándar para ciudadanos y artesanos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 0,
    maxInventoryWeight: 400,
    workers: [],
    inventory: [],
    unlockCost: [{ name: "Bloques de Piedra", amount: 90, icon: "🧱" }, { name: "Tablas", amount: 50, icon: "🪵" }],
  },
  {
    id: "b_manor",
    name: "Mansión Señorial (Tier 3)",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "locked",
    tier: 3,
    icon: "🏰",
    description: "Viviendas de alta densidad y palacetes para la élite dirigente.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 600,
    workers: [
      { id: "w1", professionRequired: "Mayordomo", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Sirviente", role: "trabajador", efficiency: 0 },
    ],
    inventory: [],
    unlockCost: [{ name: "Piedra Labrada", amount: 200, icon: "🧱" }, { name: "Vidrio", amount: 30, icon: "🧪" }],
  },
  {
    id: "b_aqueduct",
    name: "Pozo Público / Acueducto",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "existing",
    tier: 1,
    icon: "🏛️",
    description: "Distribución de agua limpia a los barrios y factorías.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 1,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", npcName: "Lucan", professionRequired: "Fontanero Feudal", role: "supervisor", efficiency: 95 },
    ],
    inventory: [
      { id: "city_water", name: "Agua de Acueducto", icon: "💧", quantity: 300, maxCapacity: 500, unit: "litros", category: "Agua" },
    ],
    location: { x: 3070, y: 3090 },
  },
  {
    id: "b_bathhouse",
    name: "Casa de Baños",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "locked",
    tier: 2,
    icon: "🛁",
    description: "Mantenimiento de la higiene pública para evitar epidemias.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", professionRequired: "Encargado de Baños", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Limpiador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "soap", name: "Jabones y Esencias", icon: "🧼", quantity: 0, maxCapacity: 100, unit: "pastillas", category: "Higiene" },
    ],
    unlockCost: [{ name: "Piedra", amount: 60, icon: "🪨" }, { name: "Leña", amount: 30, icon: "🔥" }],
  },
  {
    id: "b_tavern",
    name: "Taberna / Posada",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "existing",
    tier: 1,
    icon: "🍺",
    description: "Centro de ocio urbano que mantiene la felicidad de la población.",
    durability: 95,
    maxDurability: 100,
    efficiency: 95,
    level: 1,
    maxWorkers: 3,
    maxInventoryWeight: 400,
    workers: [
      { id: "w1", npcName: "Griselda Tabernera", professionRequired: "Posadero", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Camarero", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Músico", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "ale_kegs", name: "Barriles de Hidromiel", icon: "🍺", quantity: 35, maxCapacity: 100, unit: "barriles", category: "Bebida" },
    ],
    location: { x: 3040, y: 3140 },
  },
  {
    id: "b_marketplaza",
    name: "Plaza del Mercado",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "existing",
    tier: 1,
    icon: "⚖️",
    description: "Centro de intercambio de bienes de consumo diario.",
    durability: 100,
    maxDurability: 100,
    efficiency: 90,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", npcName: "Vane Mercader", professionRequired: "Pregonero", role: "supervisor", efficiency: 90 },
      { id: "w2", professionRequired: "Asistente", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "market_stalls", name: "Excedentes del Mercado", icon: "🧺", quantity: 60, maxCapacity: 200, unit: "cestas", category: "Consumo" },
    ],
    location: { x: 3080, y: 3100 },
  },
  {
    id: "b_postoffice",
    name: "Oficina de Correos / Mensajería",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "locked",
    tier: 2,
    icon: "✉️",
    description: "Infraestructura para conectar asentamientos lejanos con mensajeros.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 200,
    workers: [
      { id: "w1", professionRequired: "Maestro de Postas", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Jinete Mensajero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "letters", name: "Cartas y Despachos", icon: "📜", quantity: 0, maxCapacity: 100, unit: "cartas", category: "Mensajería" },
    ],
    unlockCost: [{ name: "Tablas", amount: 40, icon: "🪵" }, { name: "Cuero", amount: 15, icon: "🟫" }],
  },
  {
    id: "b_courthouse",
    name: "Corte de Justicia",
    category: "residential",
    categoryLabel: "Civil y Vivienda",
    categoryIcon: "🏠",
    status: "locked",
    tier: 2,
    icon: "⚖️",
    description: "Gestión del orden civil, resolución de disputas y leyes.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", professionRequired: "Juez Feudal", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Alguacil", role: "supervisor", efficiency: 0 },
    ],
    inventory: [
      { id: "laws", name: "Tomos de Leyes", icon: "📖", quantity: 0, maxCapacity: 50, unit: "tomos", category: "Legal" },
    ],
    unlockCost: [{ name: "Piedra", amount: 100, icon: "🧱" }, { name: "Pergaminos", amount: 20, icon: "📜" }],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 5. EDUCATIVO, CIENTÍFICO Y TECNOLÓGICO
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_artisanguild",
    name: "Gremio de Artesanos",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 2,
    icon: "📐",
    description: "Escuela técnica para mejorar la eficiencia de los obreros.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 400,
    workers: [
      { id: "w1", professionRequired: "Gran Maestro Gremial", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Instructor", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Aprendiz", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "blueprints", name: "Planos y Esquemas", icon: "📐", quantity: 0, maxCapacity: 80, unit: "planos", category: "Tecnología" },
    ],
    unlockCost: [{ name: "Tablas", amount: 90, icon: "🪵" }, { name: "Herramientas", amount: 15, icon: "🔨" }],
  },
  {
    id: "b_scriptorium",
    name: "Scriptorium",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 1,
    icon: "📜",
    description: "Copia de libros y documentos para preservar el conocimiento.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 200,
    workers: [
      { id: "w1", professionRequired: "Maestro Escriba", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Copista", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "manuscripts", name: "Manuscritos Iluminados", icon: "📜", quantity: 0, maxCapacity: 100, unit: "manuscritos", category: "Cultura" },
    ],
    unlockCost: [{ name: "Madera", amount: 50, icon: "🪵" }, { name: "Pieles", amount: 20, icon: "🐺" }],
  },
  {
    id: "b_library",
    name: "Biblioteca Pública",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 2,
    icon: "📚",
    description: "Almacén de patentes y descubrimientos de la civilización.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 350,
    workers: [
      { id: "w1", professionRequired: "Bibliotecario Mayor", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Archivero", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "books", name: "Compendios de Saber", icon: "📚", quantity: 0, maxCapacity: 200, unit: "libros", category: "Saber" },
    ],
    unlockCost: [{ name: "Piedra", amount: 80, icon: "🧱" }, { name: "Tablas", amount: 60, icon: "🪵" }],
  },
  {
    id: "b_inventorsguild",
    name: "Gremio de Inventores (I+D)",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 3,
    icon: "💡",
    description: "Desarrollo de nuevas tecnologías, mecanismos y planos.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", professionRequired: "Inventor Visionario", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Ingeniero", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Mecánico", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Asistente", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "prototypes", name: "Prototipos Mecánicos", icon: "⚙️", quantity: 0, maxCapacity: 50, unit: "artilugios", category: "Invención" },
    ],
    unlockCost: [{ name: "Planchas de Metal", amount: 40, icon: "🛡️" }, { name: "Vidrio", amount: 30, icon: "🧪" }],
  },
  {
    id: "b_militaryacademy",
    name: "Academia Militar",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 2,
    icon: "⚔️",
    description: "Entrenamiento teórico y estratégico para comandantes.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", professionRequired: "Táctico Veterano", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Cadete Oficial", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "war_maps", name: "Mapas de Guerra y Tácticas", icon: "🗺️", quantity: 0, maxCapacity: 40, unit: "mapas", category: "Estrategia" },
    ],
    unlockCost: [{ name: "Piedra Labrada", amount: 100, icon: "🧱" }, { name: "Armas", amount: 20, icon: "⚔️" }],
  },
  {
    id: "b_observatory",
    name: "Observatorio Astrológico",
    category: "tech",
    categoryLabel: "Ciencia y Tech",
    categoryIcon: "🎓",
    status: "locked",
    tier: 3,
    icon: "🔭",
    description: "Estudio del cielo para la navegación y bonificaciones de progreso.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 200,
    workers: [
      { id: "w1", professionRequired: "Astrónomo Real", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Calculista", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "astrolabes", name: "Astrolabios y Lentes", icon: "🔭", quantity: 0, maxCapacity: 30, unit: "instrumentos", category: "Óptica" },
    ],
    unlockCost: [{ name: "Vidrio Pulido", amount: 50, icon: "🧪" }, { name: "Piedra Labrada", amount: 140, icon: "🧱" }],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 6. CULTURAL, RELIGIOSO Y MONUMENTAL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_amphitheater",
    name: "Anfiteatro / Coliseo",
    category: "culture",
    categoryLabel: "Cultura y Fe",
    categoryIcon: "🎨",
    status: "locked",
    tier: 3,
    icon: "🎭",
    description: "Espectáculos masivos para el control de la felicidad social.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 3,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", professionRequired: "Director de Juegos", role: "administrador", efficiency: 0 },
      { id: "w2", professionRequired: "Gladiador / Actor", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Gladiador / Actor", role: "trabajador", efficiency: 0 },
    ],
    inventory: [],
    unlockCost: [{ name: "Piedra Labrada", amount: 250, icon: "🧱" }, { name: "Madera", amount: 100, icon: "🪵" }],
  },
  {
    id: "b_chapel",
    name: "Capilla Local",
    category: "culture",
    categoryLabel: "Cultura y Fe",
    categoryIcon: "🎨",
    status: "existing",
    tier: 1,
    icon: "⛪",
    description: "Pequeño centro religioso para la cohesión espiritual temprana.",
    durability: 100,
    maxDurability: 100,
    efficiency: 100,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 200,
    workers: [
      { id: "w1", npcName: "Hermano Tomás", professionRequired: "Sacerdote", role: "supervisor", efficiency: 100 },
      { id: "w2", professionRequired: "Acólito", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "holy_water", name: "Agua Bendita y Óleos", icon: "🕊️", quantity: 20, maxCapacity: 50, unit: "frascos", category: "Reliquias" },
    ],
    location: { x: 3090, y: 3020 },
  },
  {
    id: "b_cathedral",
    name: "Gran Catedral o Templo",
    category: "culture",
    categoryLabel: "Cultura y Fe",
    categoryIcon: "🎨",
    status: "locked",
    tier: 3,
    icon: "🕍",
    description: "Monumento masivo que centraliza la fe y la influencia cultural.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", professionRequired: "Arzobispo", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Canónigo", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Monje", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Monje", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "golden_relics", name: "Relicarios de Oro", icon: "✨", quantity: 0, maxCapacity: 40, unit: "relicarios", category: "Tesoro Sagrado" },
    ],
    unlockCost: [{ name: "Piedra Labrada", amount: 300, icon: "🧱" }, { name: "Oro", amount: 100, icon: "💰" }],
  },
  {
    id: "b_triumpharch",
    name: "Arco del Triunfo / Monumento",
    category: "culture",
    categoryLabel: "Cultura y Fe",
    categoryIcon: "🎨",
    status: "locked",
    tier: 2,
    icon: "🏛️",
    description: "Celebra expansiones exitosas y reduce el descontento.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 0,
    maxInventoryWeight: 100,
    workers: [],
    inventory: [],
    unlockCost: [{ name: "Piedra Esculpida", amount: 120, icon: "🧱" }],
  },
  {
    id: "b_relicmuseum",
    name: "Museo de Reliquias",
    category: "culture",
    categoryLabel: "Cultura y Fe",
    categoryIcon: "🎨",
    status: "locked",
    tier: 2,
    icon: "🏺",
    description: "Exhibición de artefactos que atrae inmigración y prestigio.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", professionRequired: "Conservador", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Guía", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "ancient_artifacts", name: "Artefactos Antiguos", icon: "🏺", quantity: 0, maxCapacity: 50, unit: "piezas", category: "Reliquia" },
    ],
    unlockCost: [{ name: "Tablas", amount: 60, icon: "🪵" }, { name: "Piedra", amount: 70, icon: "🧱" }],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 7. MILITAR Y DEFENSIVO
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "b_guardpost",
    name: "Puesto de Guardia",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "existing",
    tier: 1,
    icon: "🗼",
    description: "Pequeña torre para vigilar caminos y alertar de amenazas.",
    durability: 95,
    maxDurability: 100,
    efficiency: 90,
    level: 1,
    maxWorkers: 2,
    maxInventoryWeight: 300,
    workers: [
      { id: "w1", npcName: "Sargento Varek", professionRequired: "Guardia", role: "supervisor", efficiency: 95 },
      { id: "w2", professionRequired: "Centinela", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "torches", name: "Antorchas de Señal", icon: "🔥", quantity: 20, maxCapacity: 50, unit: "antorchas", category: "Vigilancia" },
      { id: "spears", name: "Lanzas de Guardia", icon: "🗡️", quantity: 10, maxCapacity: 30, unit: "armas", category: "Armamento" },
    ],
    location: { x: 3300, y: 3000 },
  },
  {
    id: "b_barracks",
    name: "Cuartel de Infantería",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 2,
    icon: "⚔️",
    description: "Reclutamiento y entrenamiento de tropas de combate cuerpo a cuerpo.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 6,
    maxInventoryWeight: 800,
    workers: [
      { id: "w1", professionRequired: "Capitán Instructor", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Sargento", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Recluta", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Recluta", role: "trabajador", efficiency: 0 },
      { id: "w5", professionRequired: "Recluta", role: "trabajador", efficiency: 0 },
      { id: "w6", professionRequired: "Recluta", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "swords", name: "Espadas de Acero", icon: "⚔️", quantity: 0, maxCapacity: 40, unit: "armas", category: "Armamento" },
      { id: "shields", name: "Escudos Pesados", icon: "🛡️", quantity: 0, maxCapacity: 40, unit: "defensa", category: "Blindaje" },
    ],
    unlockCost: [{ name: "Piedra", amount: 120, icon: "🧱" }, { name: "Tablas", amount: 80, icon: "🪵" }],
  },
  {
    id: "b_archeryrange",
    name: "Campo de Tiro",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 2,
    icon: "🎯",
    description: "Entrenamiento de arqueros, ballesteros o unidades de proyectiles.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 500,
    workers: [
      { id: "w1", professionRequired: "Maestro Arquero", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Tirador", role: "trabajador", efficiency: 0 },
      { id: "w3", professionRequired: "Tirador", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Tirador", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "bows", name: "Arcos Largos", icon: "🏹", quantity: 0, maxCapacity: 40, unit: "arcos", category: "Armas" },
      { id: "arrows", name: "Carcajes de Flechas", icon: "🎯", quantity: 0, maxCapacity: 300, unit: "flechas", category: "Munición" },
    ],
    unlockCost: [{ name: "Madera", amount: 90, icon: "🪵" }, { name: "Cuerdas", amount: 30, icon: "🧵" }],
  },
  {
    id: "b_siegeworkshop",
    name: "Taller de Asedio",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 3,
    icon: "💣",
    description: "Fabricación de catapultas, arietes, balistas y cañones pesados.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 1200,
    workers: [
      { id: "w1", professionRequired: "Maestro Artillero", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Ingeniero Militar", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Operario", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Operario", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "catapults", name: "Piezas de Catapulta", icon: "⚙️", quantity: 0, maxCapacity: 10, unit: "máquinas", category: "Asedio" },
    ],
    unlockCost: [{ name: "Vigas", amount: 100, icon: "🏗️" }, { name: "Metal", amount: 50, icon: "🛡️" }],
  },
  {
    id: "b_reinforcedwall",
    name: "Muralla y Puerta Reforzada",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 2,
    icon: "🏰",
    description: "Perímetro defensivo modular para rodear las factorías urbanas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 2,
    maxInventoryWeight: 400,
    workers: [
      { id: "w1", professionRequired: "Capitán de Puerta", role: "supervisor", efficiency: 0 },
      { id: "w2", professionRequired: "Centinela", role: "trabajador", efficiency: 0 },
    ],
    inventory: [],
    unlockCost: [{ name: "Piedra Labrada", amount: 200, icon: "🧱" }, { name: "Troncos", amount: 100, icon: "🪵" }],
  },
  {
    id: "b_castle",
    name: "Fortaleza / Castillo",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 3,
    icon: "👑",
    description: "Centro defensivo final, cuartel general del ejército y último bastión.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 6,
    maxInventoryWeight: 2000,
    workers: [
      { id: "w1", professionRequired: "Señor de la Guerra", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Mariscal", role: "administrador", efficiency: 0 },
      { id: "w3", professionRequired: "Caballero", role: "supervisor", efficiency: 0 },
      { id: "w4", professionRequired: "Soldado", role: "trabajador", efficiency: 0 },
      { id: "w5", professionRequired: "Soldado", role: "trabajador", efficiency: 0 },
      { id: "w6", professionRequired: "Soldado", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "banner", name: "Estandartes de Guerra", icon: "🚩", quantity: 0, maxCapacity: 20, unit: "estandartes", category: "Prestigio" },
    ],
    unlockCost: [{ name: "Piedra Labrada", amount: 400, icon: "🧱" }, { name: "Vigas", amount: 200, icon: "🏗️" }, { name: "Oro", amount: 200, icon: "💰" }],
  },
  {
    id: "b_warshipyard",
    name: "Astillero de Guerra",
    category: "military",
    categoryLabel: "Militar y Defensa",
    categoryIcon: "🛡️",
    status: "locked",
    tier: 3,
    icon: "🚢",
    description: "Construcción de navíos militares para defender rutas marítimas.",
    durability: 100,
    maxDurability: 100,
    efficiency: 0,
    level: 0,
    maxWorkers: 4,
    maxInventoryWeight: 1500,
    workers: [
      { id: "w1", professionRequired: "Maestro Carpintero Naval", role: "maestro", efficiency: 0 },
      { id: "w2", professionRequired: "Calafateador", role: "supervisor", efficiency: 0 },
      { id: "w3", professionRequired: "Obrero Naval", role: "trabajador", efficiency: 0 },
      { id: "w4", professionRequired: "Obrero Naval", role: "trabajador", efficiency: 0 },
    ],
    inventory: [
      { id: "ship_timbers", name: "Maderos Curvos Navales", icon: "🪵", quantity: 0, maxCapacity: 100, unit: "maderos", category: "Naval" },
    ],
    unlockCost: [{ name: "Vigas de Roble", amount: 150, icon: "🏗️" }, { name: "Lonas de Tela", amount: 60, icon: "🧶" }],
  },
];
